export enum UserStatus {
  WAITING_FOR_A_TASK = 'WAITING_FOR_A_TASK',

  BUSY = 'BUSY',

  TEMPORARILY_INACTIVE = 'TEMPORARILY_INACTIVE',

  ACADEMIC_LEAVE = 'ACADEMIC_LEAVE',

  DELETED = 'DELETED',

  BANNED = 'BANNED',
}
